services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: medicos_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: --wiredTigerCacheSizeGB 0.5

volumes:
  mysql_data:
  mongo_data: