### Raíz
GET http://localhost:8000/

### Health check
GET http://localhost:8000/health

### CREATE — insertar un especialista
POST http://localhost:8000/especialistas/
Content-Type: application/json

{
  "nombre": "Dr. Juan Pérez",
  "especialidad": "Cardiología",
  "ubicacion": {
    "ciudad": "CDMX",
    "estado": "Ciudad de México"
  },
  "calificacion_global": 4.5,
  "total_resenas": 10,
  "fuente": "doctoralia",
  "url_perfil": "https://doctoralia.com.mx/dr-juan-perez"
}

###  READ ALL — listar con filtros
GET http://localhost:8000/especialistas/?especialidad=Cardiología&ciudad=CDMX

### READ ONE
GET http://localhost:8000/especialistas/69dfe8ec39dfd8e08184df56

### DELETE — eliminar por id
DELETE http://localhost:8000/especialistas/69dfe8ec39dfd8e08184df56
